# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: kotlin-and-cloud-native-mongo
    image: mongo:4.4.4-bionic
    restart: unless-stopped
    ports:
    - 27117:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: users